version: '3'

services:
  nginx:
    image: gashnikova/my_nginx:latest
    ports:
      - 80:80
    depends_on:
      - php

  php:
    image: gashnikova/my_apache:latest      
    ports:
      - 8081:80
    container_name: my_apache
    


